#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Miyawaki Kaito
# SPDX-License-Identifier: BSD-3-Clause

x = int(input())
divisors = []

ans = 0
for num in range(1, x+1):
    if x % num == 0:
        ans += 1
        print(num, end = " ")


print("\nつまり約数の数は" + str(ans)) 
