#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Miyawaki Kaito
# SPDX-License-Identifier: BSD-3-Clause

import math

x = float(input())
y = float(input())

while True:
    read = input()
    if read == 'GCD':
        print(math.gcd(x, y))
    elif read == 'LCM':
        print(math.lcm(x, y))
    else:
        print('計算できません')
        break


