#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Miyawaki Kaito
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 1
for line in sys.stdin: #for 変数 in オブジェクト
    try:
        ans *= int(line)
    except:
        ans *= float(line)

print(ans)

